33 email auth
JaeMyeongSon/KNU-AI-BACKEND pull request #34
Opened 2023-10-05 13:23 UTC by oyoungsun

궁금한 점이 있습니다

<img width="520" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/ad690ced-3eb5-4421-9442-fc9da2100597">
user service.createUser의 경우 
1. 이메일 중복검사
2. 이메일 인증번호 일치 여부 검사
3. 유저 생성
의 단계를 통해 회원가입이 됩니다

2번의 경우에 
<img width="529" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/cde0defa-f85a-4d03-92c4-fb1d8b6966cf">
1. 현재시간-5분 구하기
2. email repository에서 email, verify일치하고 현재시간-5분보다 앞에 생성되었으며 생성시간 기준 가장 최신것만 가져와서 (없을경우 error날림)
3. 회원가입시 보낸 인증번호와 db에서 가져온 인증번호가 일치하면
4.  return true
를 보내는 구조인데, 

출력 문을 보면 
```
중복 통과 user3@naver.com
verifyEmail:  user3@naver.com 123456
회원가입 시각 :  2023-10-05T13:13:02.534Z
회원가입 시각 :  2023-10-05T13:08:02.534Z
이메일 인증 통과 123456
최종 하나만 출력 Email {
  id: '7',
  email: 'user3@naver.com',
  verify: '123456',
  createdAt: 2023-10-05T13:12:03.345Z
}
성공
```
으로 나오고 있습니다
그런데 저의 생각으로는
```
-----createUser시작--------
중복 통과 user3@naver.com
--------verifyEmail시작----
verifyEmail:  user3@naver.com 123456
회원가입 시각 :  2023-10-05T13:13:02.534Z
회원가입 시각 :  2023-10-05T13:08:02.534Z
최종 하나만 출력 Email {
  id: '7',
  email: 'user3@naver.com',
  verify: '123456',
  createdAt: 2023-10-05T13:12:03.345Z
}
성공
------verifyEmail끝-------
이메일 인증 통과 123456
-----createUser끝--------
```
으로 출력되어야 할 것같은데 그렇지 않아서 걸립니다

유저가 실제로 생기는것은 db에서 확인했습니다

2023-10-05 13:30 UTC, oyoungsun commented
한개 더...ㅠㅠㅠ
<img width="526" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/7ef987c8-9fa5-44f5-b385-7114d8fd9b86">
여기서 던지는  new UnauthorizedException('이미 존재하는 이메일입니다.')는

<img width="611" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/c9c4cd4a-0e27-41cc-8a05-d9c1d822c936">
스웨거에ㅓㅅ출력되는데
validTOken에서 
<img width="511" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/44b2b404-d420-4fa5-a2ab-2d5adb326f9b">
던지는 에러는 

<img width="628" alt="image" src="https://github.com/JaeMyeongSon/KNU-AI-BACKEND/assets/63745627/93bf4bde-2c82-4c2f-b39c-698938355ced">

콘솔에서 출력이 될까요..?

2023-10-06 02:21 UTC, JaeMyeongSon commented
첫 번째 질문 주신 사항에서는 인증 번호를 가져오는 부분은 방법은 많지만
기존에 구현 하셨던 로직과 유사하게 개발한다면 아래 예시를 제안 드리고 싶어요.

`
const startDate = 5분 전 시간;
const nowDate = 현재 시간;

const emailVerifyToken = await this.emailRepository.findOne({
      where: {
        email: email, 
        createdAt: Between(startDate, nowDate),
      },
      order: {
        createdAt: 'DESC',
      },
    });
    
    if (!emailVerifyToken) {
      throw new Error('만료되었거나 존재하지 않음');
    }

    if (emailVerifyToken.verify === verifyToken) {
      console.log('성공');
      return true;
    } else {
      console.log('실패');
      return false;
    }
   `

그게 아니라면, 
받아왔던 verifyToken 변수내에 인증 코드를 DB에서 조회해서 가져온 후에 5분 이내인지 확인 하는 방법도 있을거 같아요.

2023-10-06 02:44 UTC, JaeMyeongSon commented
두 번째 질문 주신 사항의 답변이에요.

말씀 주신 `throw new UnauthorizedException('이미 존재하는 이메일입니다.')` 와 같은 경우에는 
Nest.JS에서 기본적으로 제공해주고 있는 인터페이스를 사용해서 에러 처리를 하는거라 
직접적으로는 콘솔로 로그를 확인 할 수 없어요.

하지만, Exception filter를 사용해서 exception 관련 처리가 될때 에러 내용을 콘솔에 표시해주면 돼요!
해당 부분은 코드에 추가해서 올려드릴게요 :)

2023-10-06 02:47 UTC, JaeMyeongSon commented
> 두 번째 질문 주신 사항의 답변이에요.
> 
> 말씀 주신 `throw new UnauthorizedException('이미 존재하는 이메일입니다.')` 와 같은 경우에는 Nest.JS에서 기본적으로 제공해주고 있는 인터페이스를 사용해서 에러 처리를 하는거라 직접적으로는 콘솔로 로그를 확인 할 수 없어요.
> 
> 하지만, Exception filter를 사용해서 exception 관련 처리가 될때 에러 내용을 콘솔에 표시해주면 돼요! 해당 부분은 코드에 추가해서 올려드릴게요 :)



> 한개 더...ㅠㅠㅠ <img alt="image" width="526" src="https://user-images.githubusercontent.com/63745627/272918599-7ef987c8-9fa5-44f5-b385-7114d8fd9b86.png"> 여기서 던지는 new UnauthorizedException('이미 존재하는 이메일입니다.')는
> 
> <img alt="image" width="611" src="https://user-images.githubusercontent.com/63745627/272918866-c9c4cd4a-0e27-41cc-8a05-d9c1d822c936.png"> 스웨거에ㅓㅅ출력되는데 validTOken에서 <img alt="image" width="511" src="https://user-images.githubusercontent.com/63745627/272918983-44b2b404-d420-4fa5-a2ab-2d5adb326f9b.png"> 던지는 에러는 <img alt="image" width="628" src="https://user-images.githubusercontent.com/63745627/272919083-93bf4bde-2c82-4c2f-b39c-698938355ced.png">
> 콘솔에서 출력이 될까요..?

2023-10-06 05:19 UTC, gidskql6671 requested changes

2023-10-06 05:19 UTC, gidskql6671 commented on src/entities/email.ts
> +  verify: number;
인증 번호는 bigint로 할 필요는 없어보여요~

2023-10-06 05:19 UTC, gidskql6671 commented on src/users/dto/emails.dto.ts
> +  public email: string;
`@IsEmail()`, `@IsNotEmpty()` 등의 벨리데이터를 추가하면 더 좋을 것 같네요.

2023-10-06 05:19 UTC, gidskql6671 commented on src/users/dto/join.request.dto.ts
> +    example: '123456',
```suggestion
    example: 123456,
```

2023-10-06 05:19 UTC, gidskql6671 commented on src/users/users.controller.ts
> +  }
제가 실행은 해보지 않았는데, 이러면 이메일 인증 엔티티가 그대로 반환되지 않나요? 그러면 해당 반환값에 인증 번호가 들어있을 것 같은데, 혹시 맞다면 수정이 필요해보이네요.

2023-10-06 05:19 UTC, gidskql6671 commented on src/users/users.service.ts
> +  async sendVerifyToken(email: string, verifyToken: number) {
클래스 내부에서만 쓰는거면 private로 설정하는게 더 좋을 것 같아요.

2023-10-06 05:19 UTC, gidskql6671 commented on src/users/users.service.ts
> +  async verifyEmail(email: string, verifyToken: number) {
클래스 내부에서만 쓰는거면 private로 설정하는게 더 좋을 것 같아요.

2023-10-06 05:40 UTC, oyoungsun commented on src/users/dto/emails.dto.ts
> +  public email: string;
class validator는 dto에만 적용하는 거인 줄 알았는데, 생각해보니 entity로 바로 입력받는 경우도 있네요! 추가하겠습니다

2023-10-06 05:44 UTC, oyoungsun commented on src/users/users.controller.ts
> +  }
service단에서 return으로 아무것도 넘겨주지 않아서 반환 되지는 않는데, 그래도 알려주신 대로 return부분은 뺴고 작업하도록 하겠습니당

2023-10-06 05:57 UTC, gidskql6671 commented on src/users/users.controller.ts
> +  }
아하 방금 한번더 보니 따로 return은 없엇군요 ㅋㅋ

2023-10-06 06:03 UTC, oyoungsun commented
멘토님이 제안해주신 방법대로 인증번호 조회하는 쿼리 내에서 주어진 인증번호와 일치하는 것만 가져오도록 수정했습니다!
굳이 다시한번 인증번호가 일치하는지 검사할 필요가 없었네요

2023-10-06 06:53 UTC, oyoungsun commented on src/users/users.service.ts
> +  async sendVerifyToken(email: string, verifyToken: number) {
내부에서 쓰이는 함수 모두 private 처리 했습니다!

2023-10-06 06:54 UTC, oyoungsun commented on src/users/users.service.ts
> +  async verifyEmail(email: string, verifyToken: number) {
내부에서 쓰이는 함수 모두 private 처리 했습니다!

2023-10-06 06:55 UTC, oyoungsun commented on src/users/dto/join.request.dto.ts
> +    example: '123456',
이부분 빼먹었네요 수정완료했습니다

2023-10-06 06:55 UTC, oyoungsun commented on src/entities/email.ts
> +  verify: number;
int로 수정했습니다bb!!

2023-10-06 07:09 UTC, gidskql6671 commented on src/users/dto/emails.dto.ts
> +  public email: string;
이 부분 `src/entities/user.ts`가 아니라 `dto/emails.dto.ts`입니다 ㅠㅠ
해당 DTO로 인증 메일 요청 api의 바디를 처리하던데, 벨리데이터가 없어서 말씀드렸어요

2023-10-06 07:12 UTC, gidskql6671 commented on src/users/users.service.ts
> +    if (!this.verifyEmail(email, verify)) {
```suggestion
    if (!(await this.verifyEmail(email, verify))) {
```

2023-10-06 07:23 UTC, oyoungsun commented on src/users/users.service.ts
> +    if (!this.verifyEmail(email, verify)) {
1번에했던 질문을 이제 해결했네요ㅠㅠ 해결했습니다 bb

2023-10-06 07:28 UTC, oyoungsun commented on src/users/dto/emails.dto.ts
> +  public email: string;
다시 수정했습니다!!

2023-10-06 07:33 UTC, gidskql6671 commented on src/users/users.controller.ts
> +    return content;
```suggestion
async login(@InjectUser() user: User) {	  
    login(@Body() content: LoginReqDto) {
    return UsersDto.fromEntity(user);
```
커밋 꼬이신거같네요. 다시 돌아왓어요. 이런거 체크 잘 해주셔야해요

2023-10-06 07:38 UTC, gidskql6671 approved these changes
LGTM~~

2023-10-06 07:38 UTC, merged